### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by davephillips** [luckyxxl/vcv_luckyxxl#1]
I'm having some trouble building your modules for the latest VCV rack :

$ make
g++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/luckyxxl.cpp.o src/luckyxxl.cpp
g++ -fPIC -I../../include -I../../dep/include -DVERSION=dev -MMD -O3 -march=nocona -ffast-math -g -Wall -DARCH_LIN -std=c++11 -c -o build/src/Quantize.cpp.o src/Quantize.cpp
src/Quantize.cpp: In member function ‘virtual void Quantize::step()’:
src/Quantize.cpp:110:34: error: cannot convert ‘__gnu_cxx::__alloc_traits<std::allocator<rack::Input> >::value_type {aka rack::Input}’ to ‘const float*’ for argument ‘1’ to ‘float rack::getf(const float*, float)’
  const float in = getf(inputs[IN]);
                                  ^
src/Quantize.cpp:117:24: error: cannot convert ‘__gnu_cxx::__alloc_traits<std::allocator<rack::Output> >::value_type {aka rack::Output}’ to ‘float*’ for argument ‘1’ to ‘void rack::setf(float*, float)’
  setf(outputs[OUT], out);
                        ^
../../compile.mk:49: recipe for target 'build/src/Quantize.cpp.o' failed
make: *** [build/src/Quantize.cpp.o] Error 1

Btw, I updated the luckyxxl.cpp to the new format. 

Andrew Belt advised that I contact developers about the conversion error, he noted that changes in the latest engine.hpp should be accommodated. Let me know if I can help further.

**Comment by luckyxxl** [comment]
Thanks for pointing this out. There have been indeed some breaking changes in the plugin API in the master branch of Rack.
Personally I'd prefer to always support the latest official release of Rack, to keep the amount of fixing required to a minimum (or "more condensed"). Therefore, I will fix the build shortly after the next version (v0.3.3 or v0.4.0) comes out.

**Comment by luckyxxl** [comment]
Fixed by c88a83f01e72ddadf5afa3a37716d4e0909df619
