### ISSUE TITLE
Rack 0.5.1 plugin manager problem

### ISSUE THREAD

**Issue by a1laserboy** [luckyxxl/vcv_luckyxxl#10]
Hi,

I'm getting an error when plugin manager tries to download your plugins:

[warning] Could not get download URL for plugin luckyxxl

![screen shot 2017-12-19 at 20 15 41](https://user-images.githubusercontent.com/13291547/34177020-fdb3f9e6-e4f9-11e7-920c-c063879d419f.png)

**Comment by luckyxxl** [comment]
Hi,
I did a new release which includes builds for Windows and Linux. Unfortunately I can't provide Mac builds, which can cause this error, too.
