### ISSUE TITLE
Request: Distribute 1x10

### ISSUE THREAD

**Issue by LKHSogpit** [luckyxxl/vcv_luckyxxl#11]
Hi nice module any chance of a version with 1 in 2 out x10?

**Comment by luckyxxl** [comment]
There you go: 37bb4630662107ce2977c653b7f9bb73d935fcc0

Have fun, glad you find it useful ;)

**Comment by luckyxxl** [comment]
Ah sorry, didn't see that you already prepared a layout. Better put a link in the issue next time or make a pull request to THIS repo. Would have loved to guide you through modifying it yourself!

**Comment by LKHSogpit** [comment]
Nice! It is very useful. Still can I'll just forget I ever saw it...

**Comment by LKHSogpit** [comment]
Ah I'm Reading up on how to write atm, Just looking at a youtube series about C++. Posted in JW's guide
https://github.com/jeremywen/JW-Modules/wiki/Dev-FAQ-for-VCV-Rack
