### ISSUE TITLE
Another build problem

### ISSUE THREAD

**Issue by asbaklm** [luckyxxl/vcv_luckyxxl#3]
Hi there, seeing the following build problem on Ubuntu 16.04 / Mint 18

src/Quantize.cpp: In member function ‘virtual void Quantize::step()’:
src/Quantize.cpp:52:18: error: ‘floor’ is not a member of ‘std’
  const float o = std::floor(in);
                  ^
src/Quantize.cpp:52:18: note: suggested alternative:
In file included from /usr/include/features.h:367:0,
                 from /usr/include/stdlib.h:24,
                 from ../../include/util.hpp:4,
                 from ../../include/rack.hpp:3,
                 from src/luckyxxl.hpp:1,
                 from src/Quantize.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:184:1: note:   ‘floor’
 __MATHCALLX (floor,, (_Mdouble_ __x), (__const__));
 ^
src/Quantize.cpp:53:18: error: ‘floor’ is not a member of ‘std’
  const float s = std::floor((in - o) * 12.f);
                  ^
src/Quantize.cpp:53:18: note: suggested alternative:
In file included from /usr/include/features.h:367:0,
                 from /usr/include/stdlib.h:24,
                 from ../../include/util.hpp:4,
                 from ../../include/rack.hpp:3,
                 from src/luckyxxl.hpp:1,
                 from src/Quantize.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:184:1: note:   ‘floor’
 __MATHCALLX (floor,, (_Mdouble_ __x), (__const__));
 ^
../../compile.mk:50: recipe for target 'build/src/Quantize.cpp.o' failed
make: *** [build/src/Quantize.cpp.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by davephillips** [comment]
Error confirmed on Fedora 21 Linux, GCC 4.9.2.

**Comment by davephillips** [comment]
Solved by adding <cmath> to luckyxxl.hpp.

**Comment by asbaklm** [comment]
Top man! Thank you very much Mr Phillips.

**Comment by luckyxxl** [comment]
Thank you both for reporting, fixing and testing! Should be fixed in e2bdf1c3c9f775a39bff0dedc54963b4d0121262
