### ISSUE TITLE
errors building 0.4.0 version on OSX Sierra

### ISSUE THREAD

**Issue by robotfunk** [luckyxxl/vcv_luckyxxl#4]
src/Quantize.cpp:22:22: error: implicit instantiation of undefined template 'std::__1::array<char, 2>'
        std::array<char, 2> display;
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:114:65: note: 
      template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
src/Quantize.cpp:52:18: error: no member named 'floor' in namespace 'std'; did you mean simply 'floor'?
        const float o = std::floor(in);
                        ^~~~~~~~~~
                        floor
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/math.h:474:15: note: 
      'floor' declared here
extern double floor(double);
              ^
src/Quantize.cpp:53:18: error: no member named 'floor' in namespace 'std'; did you mean simply 'floor'?
        const float s = std::floor((in - o) * 12.f);
                        ^~~~~~~~~~
                        floor
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/math.h:474:15: note: 
      'floor' declared here
extern double floor(double);
              ^
src/Quantize.cpp:64:35: error: implicit instantiation of undefined template 'std::__1::array<char, 2>'
        static const std::array<char, 2> semis_sharp[12] = {
                                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:114:65: note: 
      template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
src/Quantize.cpp:79:35: error: implicit instantiation of undefined template 'std::__1::array<char, 2>'
        static const std::array<char, 2> semis_flat[12] = {
                                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tuple:114:65: note: 
      template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TYPE_VIS_ONLY array;
                                                                ^
src/Quantize.cpp:100:12: error: cannot initialize a parameter of type 'rack::Module *' with an lvalue of type 'Quantize *'
        setModule(module);
                  ^~~~~~
../../include/app.hpp:37:25: note: passing argument to parameter 'module' here
        void setModule(Module *module);
                               ^
src/Quantize.cpp:114:11: error: no matching function for call to 'createInput'
        addInput(createInput<PJ301MPort>(Vec(12, 320), module, Quantize::IN));
                 ^~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:52:7: note: candidate function [with TPort = rack::PJ301MPort] not viable: no known conversion from
      'Quantize *' to 'rack::Module *' for 2nd argument
Port *createInput(Vec pos, Module *module, int inputId) {
      ^
src/Quantize.cpp:115:12: error: no matching function for call to 'createOutput'
        addOutput(createOutput<PJ301MPort>(Vec(53, 320), module, Quantize::OUT));
                  ^~~~~~~~~~~~~~~~~~~~~~~~
../../include/rack.hpp:62:7: note: candidate function [with TPort = rack::PJ301MPort] not viable: no known conversion from
      'Quantize *' to 'rack::Module *' for 2nd argument
Port *createOutput(Vec pos, Module *module, int outputId) {
      ^
src/Quantize.cpp:120:11: error: no matching function for call to 'createParam'
        addParam(createParam<CKSS>(Vec(24, 100), module, Quantize::DISPLAY_MODE, 0, 1, 1));
                 ^~~~~~~~~~~~~~~~~
../../include/rack.hpp:41:14: note: candidate function [with TParam = rack::CKSS] not viable: no known conversion from
      'Quantize *' to 'rack::Module *' for 2nd argument
ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {
             ^
src/Quantize.cpp:121:11: error: no matching function for call to 'createParam'
        addParam(createParam<CKSS>(Vec(60, 100), module, Quantize::HOLD, 0, 1, 0));
                 ^~~~~~~~~~~~~~~~~
../../include/rack.hpp:41:14: note: candidate function [with TParam = rack::CKSS] not viable: no known conversion from
      'Quantize *' to 'rack::Module *' for 2nd argument
ParamWidget *createParam(Vec pos, Module *module, int paramId, float minValue, float maxValue, float defaultValue) {

**Comment by antoniograzioli** [comment]
same error here...

**Comment by dotinspace** [comment]
Just to chip in:

Adding `#include <cmath>` in `luckyxxl.hpp` as suggested on FB group page by Dave Phillips makes no difference, btw.

**Comment by IohannRabeson** [comment]
Same errors.
They are 2 missing includes, <cmath> and <array>.

**Comment by robotfunk** [comment]
adding
#include <cmath>
#include <array>
to the top of luckyxxl.hpp fixes it here

**Comment by antoniograzioli** [comment]
i added 

#include <cmath>
#include <array>

in luckyxxl.hpp


and 

#include "SevenSegmentDisplay.hpp"
in Quantize.cpp

**Comment by antoniograzioli** [comment]
also, rename the folder to "luckyxxl" or background will not load (unless you change them in code)

**Comment by luckyxxl** [comment]
Thanks for reporting and fixing! Should be fixed by e2bdf1c3c9f775a39bff0dedc54963b4d0121262

**Comment by antoniograzioli** [comment]
on Mac background panels don't load...SVGs are now on /Documents/Rack/plugins...

replace (in all modules):

`panel->setBackground(SVG::load("plugins/luckyxxl/res/MyModule.svg"));`

with
`panel->setBackground(SVG::load(assetPlugin(plugin, "res/MyModule.svg")));`

this way you will load backgrounds from the "res" folder relative to the plugin, instead of looking in "plugins/luckyxxl/res"

**Comment by luckyxxl** [comment]
I see, thanks, fixed in cd38feea9a001b48d6782ad67228aedbe63d6d56
