### ISSUE TITLE
make errors in gsamplerate in arch linux 

### ISSUE THREAD

**Issue by Malifick** [luckyxxl/vcv_luckyxxl#6]
make
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/Tick.cpp.o src/Tick.cpp
In file included from src/Tick.cpp:3:0:
src/SevenSegmentDisplay.hpp:4:7: warning: ‘virtual void SevenSegmentDisplay::draw(NVGcontext*)’ can be marked override [-Wsuggest-override]
  void draw(NVGcontext *vg);
       ^~~~
src/SevenSegmentDisplay.hpp:14:7: warning: ‘virtual void SevenSegmentDot::draw(NVGcontext*)’ can be marked override [-Wsuggest-override]
  void draw(NVGcontext *vg);
       ^~~~
src/Tick.cpp:26:7: warning: ‘virtual void Tick::step()’ can be marked override [-Wsuggest-override]
  void step();
       ^~~~
src/Tick.cpp: In member function ‘virtual void Tick::step()’:
src/Tick.cpp:44:32: error: ‘gSampleRate’ was not declared in this scope
  clock_phase += (bpm / 60.f) / gSampleRate * 12;
                                ^~~~~~~~~~~
src/Tick.cpp:44:32: note: suggested alternative: ‘glSampleMaski’
  clock_phase += (bpm / 60.f) / gSampleRate * 12;
                                ^~~~~~~~~~~
                                glSampleMaski
make: *** [../../compile.mk:54: build/src/Tick.cpp.o] Error 1

**Comment by asbaklm** [comment]
Also fails to compile in Mint

**Comment by luckyxxl** [comment]
Thanks, fixed by 90d16aaa2c1af2221d06c5d73c6cb37d5860c105
