### ISSUE TITLE
Linux Release

### ISSUE THREAD

**Issue by t0m5k1** [luckyxxl/vcv_luckyxxl#8]
Please can we have a Linux release?

**Comment by phdsg** [comment]
[luckyxxl-devd4fe2e2-lin.zip](https://github.com/luckyxxl/vcv_luckyxxl/files/1503880/luckyxxl-devd4fe2e2-lin.zip)

**Comment by t0m5k1** [comment]
Thank you so much :)

**Comment by luckyxxl** [comment]
Linux builds by me are now available [here](https://github.com/luckyxxl/vcv_luckyxxl/releases) or using the new Rack Plugin Management system.
Could you please report whether they work for you?
